version: "3"
services:
  threelayertest-mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    user: "10001"
    volumes:
      - /home/test/mssql/data:/var/opt/mssql/data
      - /home/test/mssql/log:/var/opt/mssql/log
      - /home/test/mssql/secrets:/var/opt/mssql/secrets
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: yourStrong(!)Password
      MSSQL_PID: Developer
    restart: unless-stopped
    ports:
      - "1433:1433"
